### ISSUE TITLE
hidden/dot files?

### ISSUE THREAD

**Issue by justinmk** [jeetsukumaran/vim-filebeagle#1]
Is there a way to show hidden files? No mention of "hidden" in the docs or repo.

Thanks!

**Comment by genotrance** [comment]
Is there any way to have gh be enabled always? It's tedious to type gh every time. I don't mind hidden files showing up.

**Comment by nicwest** [comment]
`let g:filebeagle_show_hidden=1`

**Comment by jeetsukumaran** [comment]
Thanks @nicwest !

**Comment by genotrance** [comment]
Works great - thanks!
