### ISSUE TITLE
Curious about cd and cl

### ISSUE THREAD

**Issue by shmup** [jeetsukumaran/vim-filebeagle#13]
When I press `-` and then `cd` it returns me to my previous buffer (as in, closing filebeagle). I'm curious if this is intended. It seems like filebeagle's buffer should remain visible, but maybe I'm mistaken and just used to vinegar's approach.

Just looking for clarification.

**Comment by dylnmc** [comment]
Is there a way to simply set either the buffer or global pwd to the current directory? I wouldn't mind if it also opened the file under the cursor. Why would I want to set the pwd and then return to the previous buffer (often an empty buffer), and why can't I edit the file under the cursor after setting pwd to beagle's pwd?
