### ISSUE TITLE
Request: create directory

### ISSUE THREAD

**Issue by jgallen23** [jeetsukumaran/vim-filebeagle#15]
`d` to create a new directory in the current filebeagle path

**Comment by jeetsukumaran** [comment]
Thanks to @nicwest , this functionality is now available by just using the "`+`" key but specifying a directory name (as indicated by ending with a slash) rather than file. So, for example, to create a new directory "`foo`", just hit `+` and type "`foo/`".

**Comment by airblade** [comment]
This is very useful!
