### ISSUE TITLE
"No mapping found" when open a directory

### ISSUE THREAD

**Issue by justinmk** [jeetsukumaran/vim-filebeagle#16]
Haven't had a chance to debug, but it's easy enough to find out if it's only me with this problem. Open any directory with filebeagle:

    :e .

Then the status area shows "No mapping found" message.

**Comment by jeetsukumaran** [comment]
I cannot reproduce this. I get ``"." is a directory``.

**Comment by justinmk** [comment]
This was my fault, sorry for the noise.
