### ISSUE TITLE
Feature Request: add functionality to create directories when adding files

### ISSUE THREAD

**Issue by elasticdog** [jeetsukumaran/vim-filebeagle#39]
I'd love a means of creating new files within a new directory, either by exposing the `netrw-d` functionality to explicitly create a directory, or just automatically creating parent directories that don't exist when you add files via `+` or `%`.

**Comment by jeetsukumaran** [comment]
This is straying close to violating the "just a file browser" spirit of this, but I suppose as there already is support for creating new files, it would not be too far a stretch to allow new directories as well. 

So, I'll put this on the TODO list. May be a while before I get to it, though.

**Comment by nicwest** [comment]
doesn't it already do this? https://asciinema.org/a/63xcnrmzjtresm5ueu2ynenx8

**Comment by jeetsukumaran** [comment]
Ha @nicwest, it indeed does! In fact, I believe you kindly added that functionality in March of last year (6b1b4cf5). Thank you for that again, and thank you for pointing it out. Shows you how frazzled things are that I cannot keep on top of features.

**Comment by nicwest** [comment]
@jeetsukumaran no problemo :)
@elasticdog does this behave as you expect?

**Comment by elasticdog** [comment]
Ahh, so my issue was that I was trying to open the buffer with `%` rather than create the file first with `+`. It makes sense that it wouldn't create the intermediate directories when you haven't actually saved things yet, so the `E212: Can't open file for writing` message I was seeing would be expected and I'll remember to create the file first. Thanks for the quick response, and sorry for the noise.
