### ISSUE TITLE
seems to get confused by C:\ paths

### ISSUE THREAD

**Issue by justinmk** [jeetsukumaran/vim-filebeagle#4]
quick steps to reproduce:
- At command line, enter `vim .vim`
- FileBeagle opens and shows path `"C:\Users/jkeyes/.vim/"` in the statusline
- Press `-` to go up
- statusline shows `"C:/C:/Users/jkeyes/.vim/"`
  - no files are shown (even after `gh`)
- press `-` again
- status line shows `"C:/` (and the corresponding directory contents are shown in the buffer)
  - it should be in `C:/Users/`

I also noticed that if I drill down into a directory, the status line shows an extra `\` for each drill-down, eg: `"C:\Users\jkeyes\.vim\\bundle"`. Also notice that the slashes changed from `/` to `\`. (Personally I prefer `/`, no need to preserve stupid Windows conventions).

For path handling logic I would look at tpope's plugins, eg maybe these functions in fireplace.vim:

https://github.com/tpope/vim-fireplace/blob/master/plugin/fireplace.vim#L1234

https://github.com/tpope/vim-fireplace/blob/master/plugin/fireplace.vim#L1286

**Comment by jschnarr** [comment]
Great plugin.

The current version doesn't work for Vim on Windows with forward-slashes (shellslash) enabled. It's wrong to assume back-slashes on Windows.

The two places where you condition based on the path separator should be changed to this:

if (has("win16") || has("win32") || has("win64")) && !&shellslash

That fixed it for me.

**Comment by jeetsukumaran** [comment]
Thanks for pointing this put *and* the suggested fix. I have implemented this. Please let me know if it works.

**Comment by jschnarr** [comment]
It needs one tweak. I submitted a pull request.
