### ISSUE TITLE
prevent <leader> f mapping

### ISSUE THREAD

**Issue by turnspike** [jeetsukumaran/vim-filebeagle#45]
Hi there, nice plugin. I wish to prevent the leader f mapping as I use it for other things.

The below doesn't work for me:

```
let g:filebeagle_suppress_keymaps=1
Plug 'jeetsukumaran/vim-filebeagle'
map <silent> - <Plug>FileBeagleOpenCurrentBufferDir
```

Can you please advise - thank you.

**Comment by nicwest** [comment]
I can't reproduce this with version 8.0.586. the `g:filebeagle_suppress_keymaps = 1` appears to be working as expected.

**Comment by jeetsukumaran** [comment]
Ditto, @nicwest. @turnspike can you please confirm version? Thanks

**Comment by turnspike** [comment]
This is now working in NVIM v0.2.0 I think I had to restart my session instead of just reloading my config, very sorry I should have tried that first :sweat_smile: Thanks again for the sweet plugin.
