### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by jlanzarotta** [jeetsukumaran/vim-filebeagle#47]
Hello,

Just starting using filebeagle and so far it is working well.  There is however a small issue when filebeagle is closed, the title on the window is not restored.

After looking at the code, it looks like the code in question was simply commented out...

In the directory_viewer.wipe_and_restore() method...

```
        if has("title")
            let &titlestring = self.old_titlestring
        endif
```

Is this something that was inadvertently commented out or by design?

Thanks,

**Comment by jeetsukumaran** [comment]
Hi, 

To be honest, I'm not sure any more! You could try uncommenting the code, and, if it works OK, submit a PR?

**Comment by jlanzarotta** [comment]
When I uncommented the code, every worked fine.  I will perform some more testing before submitting a change.

**Comment by nicwest** [comment]
sounds like https://github.com/jeetsukumaran/vim-filebeagle/issues/34

**Comment by jeetsukumaran** [comment]
It sure is. @nicwest on the ball, as usual! Will push a change uncommenting it and close both issues. We can always revert, I suppose, if anything comes up. 7dd37c6
