### ISSUE TITLE
Is there any meaningful difference between this and vim-vinegar?

### ISSUE THREAD

**Issue by superDuperCyberTechno** [jeetsukumaran/vim-filebeagle#50]
They seem to do _exactly_ the same.

**Comment by jeetsukumaran** [comment]
``vim-vinegar`` relies on ``netrw`` for all its actual filesystem functionality.

This uses completely native and organic (from-scratch) VimScript for its filesystem functionality.

What you choose and why is up to you.

**Comment by superDuperCyberTechno** [comment]
Interesting. Have you considered using `h` and `l` for horizontal file navigation (entering/exiting directories, opening files).

**Comment by nicwest** [comment]
it does that....

**Comment by superDuperCyberTechno** [comment]
Sorry, I didn't get that from the docs.

Anyway, vim-vinegar doesn't, that's a pretty meaningful difference. To me, at least.

Thanks.
