### ISSUE TITLE
add C-t mapping

### ISSUE THREAD

**Issue by mckellyln** [jeetsukumaran/vim-filebeagle#52]
Hi,
Thank you for filebeagle, it is great.
Is it possible, as a configuration option, to add <C-t> to filebeagle for opening file in a new tab (just like 't') ?
But do this mapping only in filebeagle windows ?
Or would I have to edit the .vim plugin/autoload ?
thank you,
mark

**Comment by jeetsukumaran** [comment]
Isn't this already provided? I.e., ``t`` on a file entry opens it in a new tab?

**Comment by mckellyln** [comment]
HI.  Yes 't' works - but I have other plugins that open things in tabs with C-t and so I wanted to do the same.
I can go thru the plugin code to add this, but I was wondering if there was a configuration change I could make in my .vimrc to get this more simply.
thx again

**Comment by mckellyln** [comment]
I decided to add this line to the plugin:
            nmap <buffer> <silent> <C-t> <Plug>(FileBeagleBufferTabVisitTarget)
I'll just have to merge it into updates manually
Thx again for your work.

**Comment by mckellyln** [comment]
Closing
